import { useEffect, useState } from "react";
import { Alert, Button, Empty, Select, Skeleton, Space, Tag } from "antd";
import { useSearchParams } from "react-router-dom";
import { listProjectSnapshots } from "../../api/projects";
import type { ProjectSnapshot } from "../../api/project-types";
import { getDiff, type Diff } from "../../api/assistant";
import { useInspector } from "./InspectorContext";
const value = (x: unknown) => x === null ? "未提供" : typeof x === "string" ? x : JSON.stringify(x, null, 2);
export default function DiffPanel({ projectId }: { projectId: string }) {
  const [params, setParams] = useSearchParams(); const [snapshots, setSnapshots] = useState<ProjectSnapshot[]>([]);
  const [diff, setDiff] = useState<Diff>(), [pending, setPending] = useState(false), [error, setError] = useState(""); const inspector = useInspector();
  const sid = params.get("from") || snapshots[0]?.id, against = params.get("against") || "current";
  useEffect(() => { const c = new AbortController(); listProjectSnapshots(projectId, c.signal).then(r => { if (!c.signal.aborted) setSnapshots(r.items); }).catch(e => { if (!c.signal.aborted) setError(String(e)); }); return () => c.abort(); }, [projectId]);
  useEffect(() => { if (!sid) return; const c = new AbortController(); setPending(true); setError(""); getDiff(projectId, sid, against, c.signal).then(r => { if (!c.signal.aborted) setDiff(r); }).catch(e => { if (!c.signal.aborted) setError(String(e)); }).finally(() => { if (!c.signal.aborted) setPending(false); }); return () => c.abort(); }, [projectId, sid, against]);
  const set = (k: string, v: string) => setParams(old => { const n = new URLSearchParams(old); n.set(k, v); return n; });
  return <div><h3>变化与影响路径</h3><p className="atlas-muted">基于 SQLite 历史版本对比。选择变化项可定位引用依据，旧成果保留原版本。</p><Space wrap><Select aria-label="原始快照" value={sid} placeholder="选择起始快照" style={{ minWidth: 180 }} options={snapshots.map(s => ({ value: s.id, label: `快照 v${s.snapshot_version}` }))} onChange={v => set("from", v)} /><span>→</span><Select aria-label="对比版本" value={against} style={{ minWidth: 180 }} options={[{ value: "current", label: "当前工作状态" }, ...snapshots.map(s => ({ value: s.id, label: `快照 v${s.snapshot_version}` }))]} onChange={v => set("against", v)} /><Tag aria-live="polite">{pending ? "差分更新中" : `${diff?.changes.length ?? 0} 项变化`}</Tag></Space>{error && <Alert type="warning" message={error} />}{pending && !diff && <Skeleton active />}{!snapshots.length && !error && <Empty description="保存方案快照后即可比较历史版本" />}{diff?.unresolved.length ? <Alert type="warning" message="部分历史版本不可用" description={diff.unresolved.join("、")} /> : null}{diff?.changes.map(c => <button className={`atlas-diff-row ${params.get("change")===c.path?"atlas-diff-selected":""}`} aria-pressed={params.get("change")===c.path} key={c.path} onClick={() => { const fact = c.path.startsWith("facts.") ? c.path.split(".")[1] : null; inspector.inspect(fact ? { kind: "fact", id: fact } : { kind: "snapshot", id: sid! },{change:c.path}); }}><strong>{c.path}</strong><Tag>{c.kind}</Tag><div><section><small>之前</small><pre>{value(c.before)}</pre></section><section><small>之后</small><pre>{value(c.after)}</pre></section></div></button>)}{diff && !pending && !diff.changes.length && <Empty description="所选版本没有变化" />}{!!diff?.affected.length && <section><h4>受影响的成果</h4>{diff.affected.map(a => <div className={`atlas-action-card ${params.get("change")&&(!params.get("change")!.startsWith("facts.")||a.fact_ids.includes(params.get("change")!.split(".")[1]))?"atlas-diff-selected":""}`} key={a.snapshot_id}><div><strong>方案 {a.plan_id.slice(0, 8)} · {a.step_ids.length} 个步骤</strong><p>{a.reason}</p><Space wrap>{a.fact_ids.map(id => <Button size="small" key={id} onClick={() => inspector.inspect({ kind: "fact", id })}>引用 {id.slice(0, 8)}</Button>)}<Button size="small" onClick={() => setParams(old => { const n = new URLSearchParams(old); n.set("tab", "overview"); n.set("focus", a.fact_ids[0] || a.plan_id); return n; })}>突出画布路径</Button></Space></div></div>)}</section>}</div>;
}
