import {useEffect,useRef,useState} from "react";
import {Alert,Button,Drawer,Empty,Input,Select,Space,Spin,Tag,Typography} from "antd";
import {Link} from "react-router-dom";
import ForceGraph2D from "react-force-graph-2d";
import {searchNodes,getNeighbors,getOverview,type GraphNode} from "../api/graph";
import {apiGet} from "../api/client";
const colors:Record<string,string>={method:"#1677ff",concept:"#52c41a",dataset:"#fa8c16",benchmark:"#eb2f96",resource:"#722ed1",author:"#8c8c8c",paper:"#13c2c2"};
const labels:Record<string,string>={method:"方法",concept:"概念",dataset:"数据集",benchmark:"基准",resource:"资源",author:"作者",paper:"论文"};
const endpoint=(x:any)=>typeof x==="object"?x.uid:x;
const copy=(g:any)=>({nodes:g.nodes.map((n:any)=>({...n})),links:g.links.map((l:any)=>({...l,source:endpoint(l.source),target:endpoint(l.target)}))});
export default function Graph(){
 const [query,setQuery]=useState("");const [type,setType]=useState<string>();const [candidates,setCandidates]=useState<GraphNode[]>([]);const [data,setData]=useState<any>({nodes:[],links:[]});const [history,setHistory]=useState<any[]>([]);const [selected,setSelected]=useState<any>();const [relation,setRelation]=useState<string>();const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [truncated,setTruncated]=useState(false);const [width,setWidth]=useState(800);const [evidence,setEvidence]=useState<any>();
 const host=useRef<HTMLDivElement>(null);const graph=useRef<any>();const request=useRef(0);
 const apply=(g:any,merge=false)=>{setTruncated(!!g.truncated);setHistory(h=>[...h.slice(-9),copy(data)]);const old=copy(data);const byId=new Map(old.nodes.map((n:any)=>[n.uid,n]));for(const n of g.nodes)byId.set(n.uid,{...(byId.get(n.uid) as object||{}),...n});const nodes=merge?[...byId.values()]:g.nodes;const links=merge?[...new Map([...old.links,...g.links].map((l:any)=>[`${endpoint(l.source)}:${l.rel_type}:${endpoint(l.target)}`,l])).values()]:g.links;setData({nodes:nodes.map((n:any)=>({...n,color:colors[n.type]||"#999"})),links});};
 const search=async()=>{const id=++request.current;setLoading(true);setError("");try{if(!query.trim()&&!type){const g=await getOverview();if(id===request.current){apply(g);setCandidates([]);}}else{const rows=await searchNodes(query,type);if(id===request.current){setCandidates(rows);if(!rows.length)setError("没有找到匹配节点，请修改关键词或清除筛选");}}}catch(e){if(id===request.current)setError(String(e));}finally{if(id===request.current)setLoading(false);}};
 useEffect(()=>{search();return()=>{request.current++;};},[type]);
 useEffect(()=>{if(!host.current)return;const obs=new ResizeObserver(([entry])=>setWidth(entry.contentRect.width));obs.observe(host.current);return()=>obs.disconnect();},[]);
 const expand=async(uid:string,merge=true)=>{const id=++request.current;setLoading(true);try{const g=await getNeighbors(uid);if(id===request.current)apply(g,merge);}catch(e){setError(String(e));}finally{if(id===request.current)setLoading(false);}};
 return <><Typography.Title level={2}>探索知识与来源</Typography.Title><Space wrap><Input.Search placeholder="搜索概念/方法/数据集..." value={query} onChange={e=>setQuery(e.target.value)} onSearch={search} style={{width:320}}/><Select allowClear placeholder="类型过滤" value={type} onChange={setType} style={{width:150}} options={Object.keys(colors).map(t=>({value:t,label:labels[t]}))}/><Select allowClear placeholder="关系过滤" value={relation} onChange={setRelation} style={{width:180}} options={[...new Set<string>(data.links.map((l:any)=>l.rel_type))].map(t=>({value:t,label:t}))}/><Button disabled={!history.length} onClick={()=>{setData(history[history.length-1]);setHistory(h=>h.slice(0,-1));}}>返回 / 收起上次展开</Button><Button onClick={()=>graph.current?.zoomToFit(400)}>适配画布</Button><Button onClick={()=>{setQuery("");setType(undefined);getOverview().then(g=>apply(g)).catch(e=>setError(String(e)));}}>重置</Button></Space>
 <Space wrap style={{margin:"12px 0"}}>{Object.keys(colors).map(t=><Tag key={t} color={colors[t]}>{labels[t]}</Tag>)}</Space>
 {error&&<Alert type="info" message={error}/>}
 {truncated&&<Alert type="warning" message="当前只显示受限子图，可以搜索更具体的节点继续探索。"/>}
 {!!candidates.length&&<Space wrap style={{marginBottom:12}}>{candidates.map(n=><Button key={n.uid} onClick={()=>{setSelected(n);expand(n.uid,false);}}>{n.name} · {labels[n.type]}</Button>)}</Space>}
 <div ref={host} style={{height:600,background:"white",border:"1px solid #dde5ee",borderRadius:12,overflow:"hidden",position:"relative"}}>{loading&&<Spin style={{position:"absolute",top:12,left:12,zIndex:2}}/>}{!data.nodes.length&&!loading?<Empty description="暂无可显示的图谱数据" style={{paddingTop:150}}/>:<ForceGraph2D ref={graph} width={width} height={600} graphData={{nodes:data.nodes,links:relation?data.links.filter((l:any)=>l.rel_type===relation):data.links}} nodeId="uid" nodeLabel="name" linkLabel={(l:any)=>`${l.rel_type} · ${l.quality_status||"历史未核验"}`} linkDirectionalArrowLength={5} linkWidth={(l:any)=>l.quality_status==="human_verified"?2:1} onNodeClick={(n:any)=>setSelected({...n})} onLinkClick={async(l:any)=>{if(!l.passage_id){setError("此关系暂无可定位证据，不能作为已核验结论");return;}try{setEvidence(await apiGet(`/api/learning/evidence/${l.passage_id}`));}catch(e){setError(String(e));}}}/>}</div>
 <Drawer open={!!selected} onClose={()=>setSelected(undefined)} title={selected?.name}><p>{labels[selected?.type]}</p><Typography.Text copyable>{selected?.uid}</Typography.Text><p><Button onClick={()=>expand(selected.uid)}>展开邻域</Button></p>{selected?.type==="paper"&&<Link to={`/papers/${selected.uid}`}>进入论文工作区</Link>}<p>点击关系查看证据。颜色表示实体类型，不表示准确性。</p></Drawer>
 <Drawer open={!!evidence} width={650} onClose={()=>setEvidence(undefined)} title={evidence?.heading}><p>{evidence?.page?`第 ${evidence.page} 页`:"暂无可靠页码"}</p><Typography.Paragraph style={{whiteSpace:"pre-wrap"}}>{evidence?.text}</Typography.Paragraph></Drawer>
 </>;
}
