import {useEffect,useState} from "react";
import {Alert,Button,Card,Form,Input,InputNumber,Space,Table,Typography,Upload,message,Select} from "antd";
import {Link,useSearchParams} from "react-router-dom";
import {collect,uploadPdf,startExtract} from "../api/papers";
import {apiGet} from "../api/client";
export default function Manage(){
 const [params,setParams]=useSearchParams();const page=Math.max(1,Number(params.get("page"))||1);
 const [data,setData]=useState<any>({total:0,items:[]});const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<React.Key[]>([]);const [refresh,setRefresh]=useState(0);const [results,setResults]=useState<any[]>([]);const [searchBusy,setSearchBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();setLoading(true);apiGet<any>("/api/papers",{limit:20,offset:(page-1)*20,q:params.get("q")||"",parse_status:params.get("status")||undefined},c.signal).then(setData).catch(e=>{if(e.name!=="AbortError")setError(String(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[params,refresh,page]);
 return <Space direction="vertical" size="large" style={{width:"100%"}}>
 <Typography.Title level={2}>论文库</Typography.Title>{error&&<Alert closable onClose={()=>setError("")} type="error" message={error}/>}
 <Card title="添加目标论文"><Space wrap><Upload accept=".pdf" showUploadList customRequest={async opt=>{try{const r=await uploadPdf(opt.file as File);opt.onSuccess?.(r);message.success("文件已保存，正在后台解析");setRefresh(x=>x+1);}catch(e){opt.onError?.(e as Error);setError(String(e));}}}><Button type="primary">上传 PDF</Button></Upload><Link to="/tasks">查看处理进度</Link></Space><Typography.Paragraph type="secondary">原文件先保存；相同文件自动去重。解析后自动抽取有来源的知识候选，无需新手审核。</Typography.Paragraph></Card>
 <Card title="从 arXiv 采集"><Form layout="inline" initialValues={{keywords:"diffusion policy",categories:"cs.RO",start_year:2023,max_results:20}} onFinish={async v=>{setBusy(true);try{await collect({...v,keywords:v.keywords.split(/[,，]/).map((s:string)=>s.trim()).filter(Boolean),categories:v.categories.split(/[,，]/).map((s:string)=>s.trim()).filter(Boolean)});message.success("采集已提交，请在处理进度查看");}catch(e){setError(String(e));}finally{setBusy(false);}}}>
 <Form.Item name="keywords" label="关键词" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="categories" label="分类" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="start_year" label="起始年份"><InputNumber min={1900} max={2100}/></Form.Item><Form.Item name="max_results" label="数量"><InputNumber min={1} max={100}/></Form.Item><Button htmlType="submit" loading={busy}>采集</Button></Form></Card>
 <Card title="查找论文"><Input.Search placeholder="标题或摘要关键词" defaultValue={params.get("q")||""} onSearch={q=>setParams({q,page:"1"})}/><Space style={{marginTop:12}}><Select placeholder="解析状态" allowClear style={{width:150}} value={params.get("status")||undefined} options={[{value:"parsed",label:"已解析"},{value:"pending",label:"待解析"}]} onChange={s=>setParams({q:params.get("q")||"",page:"1",...(s?{status:s}:{})})}/><Button onClick={()=>setRefresh(x=>x+1)}>刷新列表</Button><Button disabled={!selected.length||busy} onClick={async()=>{setBusy(true);try{for(const uid of selected)await startExtract(String(uid));message.success("抽取任务已提交");}catch(e){setError(String(e));}finally{setBusy(false);}}}>批量抽取</Button></Space>
 <Table<any> rowKey="uid" loading={loading} dataSource={data.items} rowSelection={{selectedRowKeys:selected,onChange:setSelected}} pagination={{current:page,pageSize:20,total:data.total,showSizeChanger:false,onChange:p=>{const next=new URLSearchParams(params);next.set("page",String(p));setParams(next);}}} columns={[{title:"标题",dataIndex:"title",render:(t,r)=><Link to={`/papers/${r.uid}`}>{t}</Link>},{title:"年份",dataIndex:"year",render:y=>y||"未知"},{title:"来源",dataIndex:"source"},{title:"解析状态",dataIndex:"parse_status"}]}/></Card>
 <Card title="论文检索"><Input.Search placeholder="标题、摘要或原文关键词" loading={searchBusy} onSearch={async q=>{if(!q.trim())return;setSearchBusy(true);try{const r=await apiGet<any>("/api/search/v2",{q});setResults(r.items);if(r.mode==="keyword")message.info("当前使用本地关键词检索");}catch(e){setError(String(e));}finally{setSearchBusy(false);}}}/><Typography.Paragraph type="secondary" style={{marginTop:8}}>匹配只表示检索相关，不能证明论文质量或结论可靠。</Typography.Paragraph>{results.map(r=><Card size="small" key={r.uid} style={{marginTop:8}}><Link to={`/papers/${r.uid}`}>{r.title||r.uid}</Link><p>{r.snippet}</p><Typography.Text type="secondary">{r.hit_reason}</Typography.Text></Card>)}</Card>
 </Space>;
}
