import {useEffect,useState,useRef} from "react";
import {useParams,useSearchParams,Link} from "react-router-dom";
import {Alert,Button,Card,Checkbox,Collapse,Descriptions,Input,InputNumber,Select,Space,Spin,Tabs,Tag,Typography,Modal,message} from "antd";
import {apiGet,apiPost,apiPatch} from "../api/client";
import {startExtract} from "../api/papers";
import PaperReader from "../components/workspace/PaperReader";
import { useInspector } from "../components/workspace/InspectorContext";
const statusName:Record<string,string>={candidate:"待核验",auto_checked:"自动检查通过（非事实认证）",human_verified:"人工核验",disputed:"存在争议",withdrawn:"已撤回",legacy_unverified:"历史未核验"};
export default function PaperDetail(){
 const inspector=useInspector();
 const savedState=useRef("");
 const draftKey=`atlas:paper-draft:${useParams().uid}`;
 const {uid}=useParams();const [params,setParams]=useSearchParams();
 const [data,setData]=useState<any>();const [guide,setGuide]=useState<any>();const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [starting,setStarting]=useState(false);
 const [evidence,setEvidence]=useState<any>();const [note,setNote]=useState("");const [kind,setKind]=useState("not_understood");
 const [exp,setExp]=useState<any>({level:"example",status:"planned",code_version:"",environment:"",config:"",seed:"",metrics:"",logs:"",artifacts:""});
 const [question,setQuestion]=useState<any>({title:"",hypothesis:"",minimal_experiment:"",resources:"",failure_criterion:"",evidence:""});
 const [compareIds,setCompareIds]=useState<string[]>([]);const [compareOptions,setCompareOptions]=useState<any[]>([]);const [comparison,setComparison]=useState<any[]>([]);const [metadata,setMetadata]=useState<any>();const lock=useRef(false);const activeUid=useRef(uid);activeUid.current=uid;
 useEffect(()=>{const c=new AbortController();setData(undefined);setGuide(undefined);setError("");Promise.all([apiGet<any>(`/api/learning/papers/${uid}`,undefined,c.signal),apiGet<any>(`/api/learning/papers/${uid}/guide`,undefined,c.signal)]).then(([d,g])=>{if(c.signal.aborted)return;savedState.current=JSON.stringify(d.state);try{const cached=JSON.parse(localStorage.getItem(draftKey)||"null");if(cached?.state){d.state=cached.state;if(cached.version!==d.version)setError("本地草稿对应较早版本，已保留输入；保存前请检查当前内容。");}}catch{}setData(d);setGuide(g);localStorage.setItem("atlas:lastPaper",uid||"");}).catch(e=>{if(e.name!=="AbortError")setError(String(e));});return()=>c.abort();},[uid]);
 useEffect(()=>{if(!data)return;try{if(JSON.stringify(data.state)!==savedState.current)localStorage.setItem(draftKey,JSON.stringify({version:data.version,state:data.state}));else localStorage.removeItem(draftKey);}catch{}},[data,draftKey]);
 useEffect(()=>{if(!uid)return;try{const cached=JSON.parse(localStorage.getItem(`atlas:paper-input:${uid}`)||"null");if(cached){setExp(cached.exp);setQuestion(cached.question);setNote(cached.note||"");}}catch{}},[uid]);
 useEffect(()=>{if(uid)try{localStorage.setItem(`atlas:paper-input:${uid}`,JSON.stringify({exp,question,note}));}catch{}},[exp,question,note,uid]);
 useEffect(()=>{const focus=params.get("focus");if(!focus||!data)return;const target=document.getElementById(`atlas-check-${focus}`)||document.getElementById(`atlas-passage-${focus}`);target?.scrollIntoView?.({behavior:window.matchMedia?.("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"center"});},[data?.paper?.uid,params.get("focus"),params.get("tab")]);
 const refresh=async()=>{try{const [d,g]=await Promise.all([apiGet<any>(`/api/learning/papers/${uid}`),apiGet<any>(`/api/learning/papers/${uid}/guide`)]);if(activeUid.current===uid){savedState.current=JSON.stringify(d.state);setData((old:any)=>({...d,state:old?.state||d.state}));setGuide(g);setError("");inspector.refresh();}}catch(e){setError(String(e));}};
 const save=async(state:any)=>{if(lock.current)return;lock.current=true;setSaving(true);try{const r=await apiPatch<any>(`/api/learning/papers/${uid}`,{version:data.version,state});if(activeUid.current===uid){savedState.current=JSON.stringify(r.state);localStorage.removeItem(draftKey);setData((d:any)=>({...d,...r}));inspector.refresh();message.success("记录已保存");}}catch(e){setError(String(e));}finally{lock.current=false;setSaving(false);}};
 const showEvidence=async(id:string)=>{if(inspector.available){inspector.inspect({kind:"passage",id});return;}try{setEvidence(await apiGet(`/api/learning/evidence/${id}`));}catch(e){setError(String(e));}};
 const sources=(ids:string[])=><Space wrap>{ids.map(id=><Button size="small" key={id} onClick={()=>showEvidence(id)}>查看原文</Button>)}</Space>;
 if(!data)return <>{error?<Alert type="error" message={error}/>:<Spin/>}</>;
 const state=data.state;const docs=data.documents;const passages=docs[0]?.passages||[];
 const reading=<Space direction="vertical" size="middle" style={{width:"100%"}}>
 <PaperReader key={docs[0]?.id} uid={uid!} />
 <Alert type="info" showIcon message={docs[0]?.coverage==="fulltext"?"已保存正文片段，解析仍可能不完整":"摘要级资料"} description={docs[0]?.warnings?.join(" ")||"请上传原文，摘要无法支撑完整实验指南。"}/>
 <Space wrap><Button type="primary" loading={starting} onClick={async()=>{setStarting(true);try{await apiPost(`/api/learning/papers/${uid}/guide`);message.success("辅助解读任务已提交");}catch(e){setError(String(e));}finally{setStarting(false);}}}>生成有出处的辅助解读</Button><Button onClick={refresh}>刷新处理结果</Button><Link to="/tasks">查看处理进度</Link></Space>
 {guide?.guide&&<Card title="辅助解读"><Alert type="warning" message={guide.guide.notice} description={guide.guide.stale?"原文版本已变化，请重新生成。":`保存于 ${guide.created_at}；这是已保存内容，不是实时验证结果。`}/>{guide.guide.explanations.map((g:any,i:number)=><div key={i} style={{marginTop:16}}><Typography.Title level={5}>{g.topic}</Typography.Title><p>{g.explanation}</p>{sources(g.passage_ids)}</div>)}</Card>}
 <Card title="分步阅读"><Typography.Paragraph type="secondary">勾选仅表示读过，不代表掌握。理解检查尚未完成的部分会继续保留为学习重点。</Typography.Paragraph>
 {data.reading_tasks.map((t:any)=><Card size="small" id={`atlas-passage-${t.passage_id}`} key={t.id} style={{marginBottom:8}}><Space wrap><Checkbox disabled={saving} checked={!!state.reading[t.id]} onChange={e=>save({...state,reading:{...state.reading,[t.id]:e.target.checked}})}>{t.heading}</Checkbox><Tag>约 {t.minutes} 分钟</Tag>{sources([t.passage_id])}</Space><p>完成标准：{t.criterion}</p></Card>)}
 {!passages.length&&<p>尚无保存的章节，解析完成后刷新。</p>}</Card>
 <Card title="理解检查"><Typography.Paragraph>填写回答和证据位置，记录自己仍不理解的地方。平台不会用模型自评分宣称你已掌握。</Typography.Paragraph>{data.checks.map((c:any)=><div id={`atlas-check-${c.id}`} key={c.id} style={{marginBottom:16}}><Typography.Text strong>{c.question}</Typography.Text><Input.TextArea rows={3} value={state.answers[c.id]?.text||""} onChange={e=>setData({...data,state:{...state,answers:{...state.answers,[c.id]:{...state.answers[c.id],text:e.target.value,status:"draft"}}}})}/><Select style={{width:220,marginTop:8}} value={state.answers[c.id]?.status||"draft"} options={[{value:"draft",label:"还在思考，需要继续学习"},{value:"answered",label:"已作答，尚未外部核验"},{value:"skip",label:"暂时跳过，不计为掌握"}]} onChange={v=>setData({...data,state:{...state,answers:{...state.answers,[c.id]:{...state.answers[c.id],status:v}}}})}/></div>)}<Button loading={saving} onClick={()=>save(state)}>保存理解记录</Button></Card>
 <Card title="术语与知识依据">{data.knowledge.filter((k:any)=>k.kind==="entity"&&!["withdrawn","disputed"].includes(k.status)).map((k:any)=><Card key={k.id} size="small" style={{marginBottom:8}}><Space><Typography.Text strong>{k.payload.name}</Typography.Text><Tag>{statusName[k.status]}</Tag></Space><p>{k.quote||"暂无可定位证据"}</p>{k.passage_id&&sources([k.passage_id])}</Card>)}{!data.knowledge.length&&<p>知识仍在处理；可以先阅读原文。</p>}</Card>
 </Space>;
 const experiment=<Space direction="vertical" style={{width:"100%"}}>
 <Alert type="warning" message="复现准备与实验记录" description={data.reproduction.notice}/>{data.reproduction.code_url&&<a href={data.reproduction.code_url} target="_blank" rel="noreferrer">已登记代码链接（请确认来源）</a>}
 {data.protocol&&<Card title="维护者实测路径"><Tag>{data.protocol.scope}</Tag><p>维护者：{data.protocol.maintainer} · 实测时间：{data.protocol.tested_at}</p><a href={data.protocol.repository} target="_blank" rel="noreferrer">登记的代码仓库</a><p>版本：{data.protocol.commit}</p><p>环境：{data.protocol.environment}</p><p>资源：{data.protocol.resources}</p>{data.protocol.steps.map((s:any,i:number)=><Card key={i} size="small" title={s.title}><p>输入：{s.inputs}</p><p>操作：{s.operation}</p><p>预期产物：{s.expected_output}</p><p>验收：{s.acceptance}</p><p>排查：{s.troubleshooting}</p></Card>)}{sources(data.protocol.evidence_ids)}</Card>}<Card title="准备清单">{data.reproduction.steps.map((s:string,i:number)=><p key={s}>{i+1}. {s}</p>)}</Card>
 <Card title="记录一次实验"><Space wrap><Select value={exp.level} style={{width:180}} options={[{value:"example",label:"示例跑通"},{value:"small_scale",label:"小规模验证"},{value:"paper",label:"论文结果复现"}]} onChange={level=>setExp({...exp,level})}/><Select value={exp.status} style={{width:150}} options={[{value:"planned",label:"准备中"},{value:"failed",label:"运行失败"},{value:"completed",label:"已完成（自述）"}]} onChange={status=>setExp({...exp,status})}/></Space>
 {([["code_version","仓库及提交版本"],["environment","软硬件环境与资源要求"],["config","实验配置与数据来源"],["seed","随机种子"],["metrics","评价指标、预期结果与实际差异"],["logs","日志与失败原因"],["artifacts","结果文件位置"]] as string[][]).map(([k,label])=><div key={k} style={{marginTop:12}}><Typography.Text>{label}</Typography.Text><Input.TextArea value={exp[k]} onChange={e=>setExp({...exp,[k]:e.target.value})}/></div>)}
 <Button style={{marginTop:16}} type="primary" loading={saving} onClick={()=>save({...state,experiments:[...state.experiments,{...exp,id:crypto.randomUUID(),created_at:new Date().toISOString(),verification:"self_reported"}]})}>保存实验记录</Button></Card>
 {state.experiments.map((e:any)=><Card key={e.id} title={e.created_at}><Tag>{e.level}</Tag><Tag>{e.status}</Tag><Tag>用户记录，未经独立复现核验</Tag><Descriptions column={1} items={["code_version","environment","config","seed","metrics","logs","artifacts"].map(k=>({key:k,label:k,children:e[k]||"未记录"}))}/></Card>)}</Space>;
 const research=<Space direction="vertical" style={{width:"100%"}}>
 <Alert type="info" message="待验证研究问题，不等于创新性结论" description="图谱缺少关系不证明研究空白。先检查相关文献与实验条件，再设计最低成本的验证。"/>
 <Card title="你的研究约束">{(["compute","math","coding","interests"] as string[]).map((k,i)=><Input key={k} style={{marginBottom:8}} addonBefore={["算力","数学基础","代码能力","兴趣"][i]} value={state.profile[k]} onChange={e=>setData({...data,state:{...state,profile:{...state.profile,[k]:e.target.value}}})}/>)}<Space><span>每周投入</span><InputNumber min={1} max={80} value={state.profile.weekly_hours} onChange={v=>setData({...data,state:{...state,profile:{...state.profile,weekly_hours:v}}})}/><Button loading={saving} onClick={()=>save(state)}>保存约束</Button></Space></Card>
 <Card title="有来源的问题线索">{guide?.guide?.questions.map((q:any,i:number)=><Card size="small" key={i} title={q.title} style={{marginBottom:12}}><p>待验证假设：{q.hypothesis}</p><p>最小实验：{q.minimal_experiment}</p><p>所需资源：{q.resources}</p><p>失败判据：{q.failure_criterion}</p>{sources(q.passage_ids)}<p>覆盖范围：当前论文；更新时间：{guide.created_at}</p></Card>)}{!guide?.guide?.questions?.length&&<p>暂无有来源的问题线索。先生成辅助解读，或在下面记录自己的问题。</p>}</Card>
 <Card title="记录研究问题">{([["title","问题标题"],["hypothesis","待验证假设"],["minimal_experiment","最小验证实验"],["resources","时间、数据和算力"],["failure_criterion","什么结果会推翻假设"],["evidence","原文证据位置与待补文献"]] as string[][]).map(([k,label])=><Input.TextArea key={k} style={{marginBottom:8}} placeholder={label} value={question[k]} onChange={e=>setQuestion({...question,[k]:e.target.value})}/>)}<Button disabled={!question.title.trim()} loading={saving} onClick={()=>save({...state,questions:[...state.questions,{...question,id:crypto.randomUUID(),created_at:new Date().toISOString(),status:"hypothesis"}]})}>保存待验证问题</Button></Card>
 {state.questions.map((q:any)=><Card title={q.title} key={q.id}><p>{q.hypothesis}</p><p>验证：{q.minimal_experiment}</p><p>失败判据：{q.failure_criterion}</p><p>依据：{q.evidence}</p></Card>)}
 <Card title="跨论文证据比较"><Typography.Paragraph>搜索并选择其他论文，最多比较 8 篇；只展示已人工核验主张，不跨实验条件排名。</Typography.Paragraph><Space wrap><Select mode="multiple" maxCount={7} style={{minWidth:320}} value={compareIds} onChange={setCompareIds} showSearch filterOption={false} placeholder="按标题查找比较论文" onSearch={async q=>{try{setCompareOptions((await apiGet<any>("/api/papers",{q,limit:20})).items);}catch(e){setError(String(e));}}} options={compareOptions.filter(p=>p.uid!==uid).map(p=>({value:p.uid,label:p.title}))}/><Button onClick={async()=>{try{setComparison((await apiGet<any>("/api/learning/compare",{uids:[uid,...compareIds].filter(Boolean).join(",")})).items);}catch(e){setError(String(e));}}}>比较证据</Button></Space>{comparison.map(p=><Card key={p.uid} title={p.title} style={{marginTop:8}}><Tag>{p.comparison_status}</Tag>{p.claims.map((k:any)=><p key={k.id}>{k.quote} {k.passage_id&&sources([k.passage_id])}</p>)}{!p.claims.length&&<p>暂无已人工核验主张，不能得出比较结论。</p>}</Card>)}</Card>
 </Space>;
 return <Space direction="vertical" size="large" style={{width:"100%"}}>
 <div><Link to="/manage">← 论文库</Link><Typography.Title level={2}>{data.paper.title}</Typography.Title><Space wrap><Tag>{data.paper.year||"年份未知"}</Tag><Typography.Text copyable>{uid}</Typography.Text><a href={`/api/papers/${uid}/file`} target="_blank" rel="noreferrer">查看本地 PDF</a><Button loading={starting} onClick={async()=>{setStarting(true);try{await apiPost(`/api/papers/${uid}/fetch-fulltext`);message.success("已提交全文获取任务");}catch(e){setError(String(e));}finally{setStarting(false);}}}>获取 arXiv 全文</Button><Button onClick={()=>setMetadata({title:data.paper.title,year:data.paper.year||null,code_url:data.paper.code_url||""})}>修正元数据</Button><Button loading={starting} onClick={async()=>{setStarting(true);try{await startExtract(uid!);message.success("已提交抽取任务");}catch(e){setError(String(e));}finally{setStarting(false);}}}>重新抽取 / 重试</Button><Link to={`/roadmap?paper=${uid}`}>规划学习路线</Link></Space></div>
 {error&&<Alert type="error" closable message={error} onClose={()=>setError("")} action={<Button onClick={refresh}>重新加载</Button>}/>}
 <Space wrap>{data.stages.map((s:any)=><Tag key={s.stage} color={s.status==="failed"?"red":s.status==="done"?"green":"blue"}>{s.stage}: {s.status}{s.error&&` · ${s.error}`}</Tag>)}</Space>
 <Tag aria-live="polite">{JSON.stringify(state)!==savedState.current?"本地草稿 · 输入已保留":"服务端已保存"}</Tag>
 <Tabs activeKey={params.get("tab")||"reading"} onChange={tab=>setParams(old=>{const n=new URLSearchParams(old);n.set("tab",tab);return n;})} items={[{key:"reading",label:"读懂论文",children:reading},{key:"experiment",label:"基础复现",children:experiment},{key:"research",label:"研究方向",children:research}]}/>
 <Collapse items={[{key:"feedback",label:"遇到困难或发现问题？告诉平台",children:<Space direction="vertical" style={{width:"100%"}}><Select value={kind} style={{width:200}} options={[{value:"not_understood",label:"没理解"},{value:"unclear",label:"解释不清楚"},{value:"broken_link",label:"链接打不开"},{value:"experiment_failed",label:"实验失败"},{value:"suspected_error",label:"内容疑似有误"}]} onChange={setKind}/><Input.TextArea value={note} onChange={e=>setNote(e.target.value)} placeholder="描述遇到的问题，不需要判断知识真伪"/><Button disabled={!note.trim()} onClick={async()=>{try{await apiPost(`/api/learning/papers/${uid}/feedback`,{kind,detail:note});setNote("");message.success("已记录，等待维护者检查");}catch(e){setError(String(e));}}}>提交反馈</Button></Space>}]}/>
 <Modal open={!!evidence} title={evidence?.heading} footer={null} onCancel={()=>setEvidence(undefined)} width={850}><p>文档版本：{evidence?.document_id} · {evidence?.page?`第 ${evidence.page} 页`:"无可靠页码"}</p><Typography.Paragraph style={{whiteSpace:"pre-wrap"}}>{evidence?.text}</Typography.Paragraph></Modal>
 <Modal open={!!metadata} title="修正元数据" onCancel={()=>setMetadata(undefined)} onOk={async()=>{try{await apiPatch(`/api/papers/${uid}`,{...metadata,code_url:metadata.code_url||null});setMetadata(undefined);await refresh();}catch(e){setError(String(e));}}}><Input value={metadata?.title} onChange={e=>setMetadata({...metadata,title:e.target.value})}/><InputNumber value={metadata?.year} onChange={year=>setMetadata({...metadata,year})}/><Input placeholder="已确认来源的代码 HTTPS 链接" value={metadata?.code_url} onChange={e=>setMetadata({...metadata,code_url:e.target.value})}/></Modal>
 </Space>;
}
