import {useEffect,useState} from "react";
import {Alert,Button,Input,Modal,Select,Space,Table,Tabs,Tag,Typography} from "antd";
import CurationSources from "../components/CurationSources";
import RelationAuditPanel from "../components/RelationAuditPanel";
import {apiGet,apiPost,apiPatch} from "../api/client";
export default function Quality(){
 const [data,setData]=useState<any>({items:[],feedback:[],audit:[]});const [error,setError]=useState("");const [filter,setFilter]=useState<string>();const [active,setActive]=useState<any>();const [evidence,setEvidence]=useState<any>();const [actor,setActor]=useState("");const [reason,setReason]=useState("");const [editText,setEditText]=useState("");const [action,setAction]=useState("verify");const [busy,setBusy]=useState(false);
 const refresh=()=>apiGet<any>("/api/learning/quality").then(setData).catch(e=>setError(String(e)));
 useEffect(()=>{refresh();},[]);
 return <><Typography.Title level={2}>维护者 · 知识质量工作台</Typography.Title><Alert type="warning" message="单机维护工具：普通新手不承担审核责任" description="自动检查不是事实认证。核验需阅读证据及上下文，记录核验人和理由。旧知识需重新抽取后才能发布。此入口分流不等于多用户权限隔离。"/>
 {error&&<Alert type="error" message={error}/>}<Tabs items={[{key:"sources",label:"录入教学依据",children:<CurationSources onSaved={refresh}/>},{key:"knowledge",label:"知识候选",children:<><Space style={{margin:"16px 0"}}><Select allowClear placeholder="状态筛选" style={{width:200}} value={filter} onChange={setFilter} options={["candidate","demo_curated","auto_checked","human_verified","disputed","withdrawn","legacy_unverified"].map(v=>({value:v,label:v}))}/><Button onClick={refresh}>刷新</Button></Space><Table<any> rowKey="id" dataSource={data.items.filter((k:any)=>!filter||k.status===filter)} columns={[{title:"内容",render:(_,k)=><div>{k.payload.name||`${k.payload.src_name} → ${k.payload.rel_type} → ${k.payload.dst_name}`}<p>{k.quote}</p><Typography.Text type="secondary">{k.payload.conditions}</Typography.Text></div>},{title:"状态",dataIndex:"status",render:s=><Tag>{s}</Tag>},{title:"操作",render:(_,k)=><Button onClick={async()=>{setActive(k);setEditText(JSON.stringify(k.payload,null,2));setEvidence(undefined);setReason("");if(k.passage_id)try{setEvidence(await apiGet(`/api/learning/evidence/${k.passage_id}`));}catch(e){setError(String(e));}}}>检查证据</Button>}]}/></>},{key:"relation-audit",label:"自动诊断",children:<RelationAuditPanel/>},{key:"feedback",label:"用户困难反馈",children:<Table<any> rowKey="id" dataSource={data.feedback} columns={[{title:"论文",dataIndex:"paper_uid"},{title:"类别",dataIndex:"kind"},{title:"内容",dataIndex:"detail"},{title:"状态",dataIndex:"status"},{title:"处理",render:(_:any,r:any)=><Select value={r.status} style={{width:140}} options={[{value:"open",label:"待检查"},{value:"investigating",label:"检查中"},{value:"resolved",label:"已处理"}]} onChange={async status=>{try{await apiPatch(`/api/learning/feedback/${r.id}`,{status});await refresh();}catch(e){setError(String(e));}}}/>}]}/>},{key:"audit",label:"核验与撤回历史",children:<Table<any> rowKey="id" dataSource={data.audit} columns={[{title:"知识",dataIndex:"knowledge_id"},{title:"操作",dataIndex:"action"},{title:"维护者",dataIndex:"actor"},{title:"理由",dataIndex:"reason"},{title:"时间",dataIndex:"created_at"}]}/>}]}/>
 <Modal open={!!active} title="核验原文与适用条件" width={900} confirmLoading={busy} onCancel={()=>setActive(undefined)} onOk={async()=>{if(!actor.trim()||!reason.trim()){setError("请填写核验人和理由");return;}setBusy(true);try{if(action==="edit")await apiPatch(`/api/learning/quality/${active.id}`,{actor,reason,payload:JSON.parse(editText)});else await apiPost(`/api/learning/quality/${active.id}`,{action,actor,reason});setActive(undefined);await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}}>
 <Alert type="info" message="原文出现该词句，不等于支持候选结论。检查否定、作者归属、条件和先修推断。"/><Typography.Paragraph style={{whiteSpace:"pre-wrap",maxHeight:320,overflow:"auto",marginTop:16}}>{evidence?.text||"无可定位原文"}</Typography.Paragraph>
 <Typography.Paragraph>候选：{active?.payload.name||`${active?.payload.src_name} → ${active?.payload.rel_type} → ${active?.payload.dst_name}`}</Typography.Paragraph><p>自动检查：{active?.checks.reason||active?.checks.semantic||"未检查"}</p>
 <Space direction="vertical" style={{width:"100%"}}><Select value={action} onChange={setAction} style={{width:240}} options={[{value:"edit",label:"编辑候选（发布内容需先撤回）"},{value:"verify",label:"人工核验并发布"},{value:"dispute",label:"标记争议，移出可信路线"},{value:"withdraw",label:"撤回"},{value:"restore",label:"恢复为候选（不自动发布）"}]}/>{action==="edit"&&<Input.TextArea rows={10} value={editText} onChange={e=>setEditText(e.target.value)}/>}<Input placeholder="核验人" value={actor} onChange={e=>setActor(e.target.value)}/><Input.TextArea placeholder="理由、适用条件与检查记录" value={reason} onChange={e=>setReason(e.target.value)}/></Space>
 </Modal></>;
}
